In [2]:
%run 'qGAN.py'

In [337]:
mps = MPS(1)
mps.pin_phys(numpy.ones(2))
out0 = mps.forward(numpy.ones(2))
mps.backward(0.0001*numpy.ones(2))
out1 = mps.forward(numpy.ones(2))
(out1 - out0)/numpy.linalg.norm(out0)

array([ 0.00012137,  0.00012137])

In [73]:
mps = MPS(4)
mps.pin_phys(numpy.ones(2))
out0 = mps.forward(numpy.array([1.,0.]))
mps.backward(-0.0001*numpy.array([1.,-10.]))
out1 = mps.forward(numpy.array([1.,0.]))
out1 - out0

array([ -7.46110068e-05,   4.61055100e-04])

In [102]:
mps = MPS(4)

In [103]:
mps.pin_phys(numpy.array([0,1]))

In [104]:
x = numpy.array([1,0])
y = mps.forward(x)
for i in range(3):
    print(y)
    grad = 0.05*y
    mps.backward(grad)
    y = mps.forward(x)

[ 0.03571354  0.70232077]
[ 0.07882753  0.85883928]
[ 0.14695493  1.04493411]


In [89]:
x = numpy.array([1,0])
y = numpy.array([1,0])
out1 = mps.forward(x)
for i in range(50):
    grad = -0.05*(out1 - y)
    mps.backward(grad)
    out0 = out1
    out1 = mps.forward(x)
    print(out1, (out1-out0)/grad)

[ 0.24854994  0.84604398] [ 6.00935168  2.7083927 ]
[ 0.46584829  0.75036059] [ 5.78344085  2.26190111]
[ 0.61958171  0.67454724] [ 5.75617075  2.02071758]
[ 0.73011776  0.61139585] [ 5.81128977  1.87240833]
[ 0.80999528  0.55728684] [ 5.91943527  1.77001561]
[ 0.86776868  0.51019826] [ 6.08125888  1.68992239]
[ 0.90955218  0.46883112] [ 6.31975823  1.62161063]
[ 0.93977472  0.43224853] [ 6.68286903  1.56058707]
[ 0.96164579  0.39972181] [ 7.26308584  1.50500092]
[ 0.9774838   0.37066041] [ 8.25881155  1.45408104]
[ 0.98895844  0.34457617] [ 10.19234078   1.40744684]
[ 0.99727015  0.32106184] [ 15.05531536   1.36482645]
[ 1.00328185  0.29977613] [ 44.04418774   1.32595699]
[ 1.00761462  0.28043217] [-26.4043966    1.29056043]
[ 1.01071651  0.26278812] [-8.14719449  1.25834717]
[ 1.01291184  0.24663943] [-4.09710049  1.22902684]
[ 1.01443632  0.23181248] [-2.3613696   1.20231847]
[ 1.01546207  0.21815921] [-1.42106219  1.17795772]
[ 1.01611541  0.20555287] [-0.84508827  1.15570116]
[ 1.

In [93]:
mps.pin_phys(numpy.array([1,0]))
mps.forward(numpy.array([1,0]))

array([ 1.00687041,  0.04328306])

In [432]:
mps.relatent()
mps.units[-1].tensor[:,:,1]

array([[-0.09438549, -1.96403226],
       [ 0.78461358,  0.08077859],
       [ 0.22485233, -0.07664104]])

In [63]:
mps = MPS(3,phys_dim = 3)
mps.pin_phys(numpy.array([1,1,0]))
mps.relatent()
y = numpy.array([1,0])

In [72]:
for i in range(500):
    z = numpy.random.normal(size = 2)
    z[0] = 1.
    z = z/numpy.linalg.norm(z)
    out = mps.forward(z)
    grad = -0.01*(out - y)
    mps.backward(grad)
    if i % 50 == 0:
        print(out, grad)

[ 1.10447315 -0.03804628] [-0.00104473  0.00038046]
[ 1.01724121  0.00545029] [ -1.72412074e-04  -5.45028967e-05]
[ 1.1333927   0.03594843] [-0.00133393 -0.00035948]
[ 1.05277531  0.02097561] [-0.00052775 -0.00020976]
[ 1.13662865 -0.00830442] [ -1.36628650e-03   8.30441615e-05]
[ 1.26482536  0.03290161] [-0.00264825 -0.00032902]
[ 0.6958651  -0.02558612] [ 0.00304135  0.00025586]
[ 0.69153104  0.03359942] [ 0.00308469 -0.00033599]
[ 1.01339993 -0.02357983] [-0.000134   0.0002358]
[ 1.12503111 -0.04360959] [-0.00125031  0.0004361 ]


In [237]:
numpy.sum((2*x)**2)

16.0

In [110]:
numpy.linalg.norm([0,0,0], ord=2)

0.0

In [109]:
numpy.

array([], dtype=float64)