# Quantum Generative Adversarial Network

This notebook contains documentation of the algorithm and testing codes. First run the following line to load the package.

In [574]:
%run 'QGAN.py'

## Classes

### Class `Pauli`

`Pauli(Xs, Zs, L)` representes a Pauli (string) operator labeled by
- two sets $\mathcal{X}$ (`Xs`) and $\mathcal{Z}$ (`Zs`)  that specifies the positions on which $\sigma^x$ and $\sigma^z$ act respectively,
- and a integer `L` that specifies the total number of qubits on which the Pauli operator acts.

$$\sigma = \mathrm{i}^{|\mathcal{X}\cap\mathcal{Z}|}\otimes_{i\in\mathcal{X}} \sigma_i^1\otimes_{i\in\mathcal{Z}}\sigma_i^3$$

`Pauli.mat()` returns the matrix representation (in terms of scipy CSR sparse array) of the Pauli operator. We assume all local operators are modeled by Pauli operators.

In [494]:
op = Pauli({1},{0,1}, 2) 
op.mat().toarray(), op

(array([[ 0.+0.j,  0.-1.j,  0.+0.j,  0.+0.j],
        [ 0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+1.j],
        [ 0.+0.j,  0.+0.j,  0.-1.j,  0.+0.j]]), σ[3, 2])

### Class `Model`

`Model(L, loc = 2)` model a system of length `L` (number of qubits) on with local operators supported on `loc` adjacent sites. Periodic boundary condition is assumed.
- `Model.ops` holds the basis of local operators.
- `Model.opdim` is the dimension of the local operator space.
- `Model.M(h)` returns the correlation matrix on the ground state on the Hamiltonian $H$ given by its vector representation `h` in the local operator space.

A simple one qubit model.

In [586]:
mdl = Model(1)
# Hilbert space dim, operator space dim, operators
mdl.dim, mdl.opdim, mdl.ops

(2, 3, [σ[1], σ[2], σ[3]])

As expected, the ground state of correlation matrix recovers the Hamiltonian nicely.

In [576]:
h = randvec(mdl.opdim)
M = mdl.M(h)
h, GS(M)

(array([ 0.41659745,  0.54776062,  0.72553764]),
 array([ 0.41659745,  0.54776062,  0.72553764]))

More serious 10-qubit model. Calculate the fidelity between the Hamiltonian and the ground state of the correlation matrix. The fidelity is typically ~ 1.

In [580]:
mdl = Model(10)
h = randvec(mdl.opdim)
M = mdl.M(h)
abs(GS(M).dot(h))

1.0

Once the model is built, the calculation of correlation matrix can be faster (~ 100ms to generate a sample of (H,M) pair for 10-qubit system). 

In [583]:
%%time
h = randvec(mdl.opdim)
M = mdl.M(h)

CPU times: user 112 ms, sys: 3.71 ms, total: 116 ms
Wall time: 120 ms


### Class `MPS`

`MPS(lenth, dim, max_dim = 8, lr = 0.001)` creates an MPS of length `length` with the output dimension `dim` (which should match the operator space dimension). The internal auxilary bond dimension is not fixed but has a upper limit set by `max_dim`. The learning rate is set by `lr`.

In [674]:
mps = MPS(5, 2)

Basic functions:
- `MPS.initialize(val)` initializes the MPS to be a two-way multiplier between the left and the right auxilary spaces, with the multiplication factor set by `val`, given the physical legs are pinned to $(1,0,0\cdots)$.
- `MPS.pin(phys_env)` pins all physical legs to the physical environment vector `phys_env`.
- `MPS.fromright(right_env)` takes the right environment vecotor `right_env` from the right end and push it all the way to the left, returning the output on the left end (typically used to pass the random source forward).
- `MPS.fromleft(left_env)` takes the left environment vector `left_env` from the left end and push it all the way to the right, returning the output on the right end (typically used to propagate the gradient backward).

In [675]:
mps.initialize(2.)
mps.pin([1,0,0])
mps.fromleft([1,3])

array([ 2.,  6.])

In our application, we will always take the right auxilary space as the latent space and the left auxilary space as the operator space. Given the physical legs pinned,
- `MPS.evaluate()` contract the right auxilary space and returns the density matrix in the operator space,
- `MPS.update(grad)` pass down the gradient of the density matrix `grad`, the MPS will be updated by ascending the gradient using the stocastic training method. (One should not expect the density matrix to be updated by the exact among of gradient, because the gradient signal is just a force acting on the MPS, how the MPS response to the force with displacement still depends on the stiffness, but different matrix element has different stiffness so the update outcome is onlu roughly along the gradient ascending direction).

In [676]:
mps.evaluate()

array([[ 4.,  0.],
       [ 0.,  4.]])

In [677]:
mps.update(0.01*numpy.array([[0,1],[1,0]]))
mps.evaluate()

array([[ 4.67782278,  1.4174439 ],
       [ 1.4174439 ,  4.85481607]])

Interface functions (with pytorch) for MPS optimization.
- `MPS.getP(h)` given the Hamiltonian (in vector form) `h`, calculate the density matrix by pinning the physical legs to $v=(1,h)$. The latent space is integrated over, s.t.
$$P(h)=MPS(h)\cdot MPS(h)^\intercal.$$
- `MPS.optimize(V)` gradient **descent** the value function `V` by updating the MPS. 

Set a objective $P_0$ to approach:

In [706]:
P0 = torch.autograd.Variable(torch.Tensor(numpy.array(
            [[0.7,0.1],
             [0.1,0.3]])))

The MPS can be simply trained by considering the quadratic loss function. Using the stocastic training approach by sampling random vectors in the latent space, the convergence looks great. 

In [733]:
mps.initialize(1.)
for i in range(200):
    P = mps.getP([0.2,0.4])
    V = torch.sum((P - P0)**2)
    mps.optimize(V)
    if i%50 == 0:
        print(P.data.numpy(), V.data.numpy())

[[ 1.  0.]
 [ 0.  1.]] [ 0.59999996]
[[ 0.77360308  0.15239084]
 [ 0.15239084  0.3149952 ]] [ 0.01113187]
[[ 0.70194817  0.09709518]
 [ 0.09709518  0.30814871]] [  8.70726362e-05]
[[ 0.7008909   0.10005269]
 [ 0.10005269  0.30040869]] [  9.66293101e-07]
